version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: slick_slides
      POSTGRES_PASSWORD: "zDqGC46-OQepMESlGvqUV6n33Y3-Q-ID"
    volumes:
      - slick_slides_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "emyWvT_3fFKDEYpO5H911MKd8bpQHE_Z"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  slick_slides_data:
