name: slick_slides
description: Create a nice looking presentations in Flutter with animations and code. Intended for techical talks and videos.
version: 0.9.0
repository: https://github.com/serverpod/slick_slides

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"
  

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  diff_match_patch: ^0.4.1
  syntax_highlight: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
